name: commec-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  # Runtime Python dependencies
  - biopython
  - numpy
  - pandas
  - pytaxonkit
  - pyyaml
  - pycountry
  # Runtime non-Python dependencies
  - blast
  - diamond>=2.1
  - hmmer
  - infernal
  - plotly
  - yaml
  - mako
  - wget
  # Development dependencies
  - pip
  - pytest
  - matplotlib
  - pip:
      - -e .
